### ISSUE TITLE
Stay longer on a station in case of same travel times

### ISSUE THREAD

**Issue by franpog859** [mchilicki/commline#1]
You should remember that sometimes user prefers to stay a little bit longer on a station if there are two ways to go somewhere but the times are equal 😉 They would have more time to prepare for some unexpected situation.
It's a thing from a real world!

**Comment by kipic96** [comment]
So you think that Search should return two possible ways to take that road. One with short staying on station and second longer staying? Or should return only one possible way with longer staying?

**Comment by franpog859** [comment]
If this is possible it should return both ways. It would be perfect! But if the case is to show only best way I suggest to return this one with longer stays.

**Comment by kipic96** [comment]
Okay, thanks for your feedback, Fran :D

**Comment by mchilicki** [comment]
@franpog859 Unfortunately, Dijkstra algorithm which I used in Commline has an issue that it can't choose a path with longer stay on a stop. For this feature, I could implement another algorithm, like the from M. Friedrich, I. Hofsäβ i S. Wekeck.

 Which you can read here: https://www.czasopismologistyka.pl/artykuly-naukowe/send/338-artykuly-na-plycie-cd-2/9371-kisielewski-kolodziej-wyszukiwanie-polaczen

If I will be doing something similar on Master's thesis, then I will return to your proposal.
